const fs = require('fs');
const USER = 'navneettsinghh';
const TOKEN = process.env.GITHUB_TOKEN;
const headers = { Accept: 'application/vnd.github+json', 'User-Agent': 'navneet-build-log' };
if (TOKEN) headers.Authorization = `Bearer ${TOKEN}`;
async function api(path){ const r=await fetch(`https://api.github.com${path}`,{headers}); if(!r.ok) throw new Error(`${r.status} ${path}`); return r.json(); }
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const repos=(await api(`/users/${USER}/repos?per_page=100&sort=pushed`)).filter(r=>!r.fork).slice(0,8);
const rows=[];
for(const r of repos){ try { const c=await api(`/repos/${USER}/${r.name}/commits?per_page=1`); const x=c[0]; if(x) rows.push({repo:r.name, message:(x.commit.message||'').split('\n')[0], date:x.commit.author?.date||x.commit.committer?.date||'', sha:x.sha.slice(0,7)}); } catch(e) {} }
rows.sort((a,b)=>new Date(b.date)-new Date(a.date));
const cards=rows.slice(0,6).map((x,i)=>`<g transform="translate(55 ${145+i*48})"><rect width="1090" height="38" rx="9" fill="#061018" stroke="#12384c"/><text x="16" y="24" fill="#00e5ff" font-family="monospace" font-size="11">${String(i+1).padStart(2,'0')}</text><text x="50" y="24" fill="#fff" font-family="monospace" font-size="11">${esc(x.repo).slice(0,25)}</text><text x="270" y="24" fill="#b9cbd4" font-family="monospace" font-size="11">${esc(x.message).slice(0,70)}</text><text x="900" y="24" fill="#6f8a99" font-family="monospace" font-size="10">${esc(x.sha)}</text><text x="1068" y="24" fill="#6f8a99" font-family="monospace" font-size="9" text-anchor="end">${esc(x.date.slice(0,10))}</text></g>`).join('');
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="500" viewBox="0 0 1200 500" role="img" aria-label="NAVNEET.OS automatic build log"><defs><linearGradient id="b" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#05080d"/><stop offset="1" stop-color="#071a28"/></linearGradient></defs><rect width="1200" height="500" rx="26" fill="url(#b)" stroke="#16455c"/><text x="55" y="48" fill="#00e5ff" font-family="monospace" font-size="19" font-weight="700">NAVNEET.OS // BUILD LOG</text><text x="55" y="70" fill="#597887" font-family="monospace" font-size="10">RECENT ENGINEERING SIGNALS · GENERATED ${new Date().toISOString()}</text><line x1="55" y1="100" x2="1145" y2="100" stroke="#12384c"/><text x="55" y="125" fill="#00e5ff" font-family="monospace" font-size="11">LATEST COMMITS ACROSS ACTIVE PUBLIC PROJECTS</text>${cards||'<text x="55" y="160" fill="#7f9aa6" font-family="monospace" font-size="12">No recent commit telemetry available.</text>'}<text x="55" y="470" fill="#4e7180" font-family="monospace" font-size="10">// GENERATED FROM PUBLIC GITHUB COMMIT METADATA · AUTOMATED · READ-ONLY TELEMETRY</text></svg>`;
fs.mkdirSync('assets',{recursive:true}); fs.writeFileSync('assets/build-log.svg',svg); console.log(`Generated build log for ${rows.length} repositories.`);
